name: CI
on: [pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v12
        with:
          java-version: adopt@1.11
      - uses: coursier/cache-action@v6
      - name: Run Tests
        run: sbt test
